version: "3.8"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    environment:
      DATABASE_URL: ${DATABASE_URL_DOCK}

    env_file:
      - .env
